# Generated by Django 5.2.8 on 2025-11-20 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='lead',
            name='mobile_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='organization_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
