# Generated by Django 5.2.8 on 2025-11-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_alter_lead_created_at_alter_lead_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='mobile_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
