# Generated by Django 5.2.8 on 2025-11-20 10:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_alter_lead_mobile_number_alter_lead_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='reference_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
