# Generated by Django 5.2.8 on 2025-11-20 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0004_alter_lead_reference_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lead',
            table='auto_lead',
        ),
    ]
