# Generated by Django 5.2.8 on 2025-11-24 10:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0006_alter_lead_created_by_alter_lead_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField()),
                ('is_delete', models.BooleanField(default=False)),
                ('company_name', models.CharField(max_length=3)),
                ('pan_number', models.CharField(max_length=9)),
                ('mobile_number', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=225)),
                ('contact_number', models.CharField(blank=True, max_length=10, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(db_column='updated_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
